obstacle_layer:
  enabled: true
  observation_sources: scan
  scan:
    data_type: LaserScan
    topic: scan
    sensor_frame: base_scan
    marking: true
    clearing: true
    expected_update_rate: 0.2       # More frequent updates
    obstacle_range: 3.0             # Increased range
    raytrace_range: 3.5             # Increased clearing range
    min_obstacle_height: 0.0        # Explicitly set
    max_obstacle_height: 2.0

inflation_layer:
  inflation_radius: 0.4             # Slightly increased
  cost_scaling_factor: 5.0          # More gradual inflation
  enabled: true