global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 2.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  resolution: 0.05
  width: 20.0
  height: 20.0
  origin_x: -10.0
  origin_y: -10.0
  transform_tolerance: 0.5

  plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}
    - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}

  static:
    map_topic: /map
    subscribe_to_updates: true

  obstacles:
    observation_sources: scan
    scan:
      data_type: LaserScan
      topic: scan
      marking: true
      clearing: true
      expected_update_rate: 0.2
      obstacle_range: 3.0
      raytrace_range: 3.5

  inflation:
    inflation_radius: 0.4
    cost_scaling_factor: 5.0