local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  transform_tolerance: 0.5

  plugins:
    - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}

  obstacles:
    observation_sources: scan
    scan:
      data_type: LaserScan
      topic: scan
      sensor_frame: base_scan
      marking: true
      clearing: true
      expected_update_rate: 0.2
      obstacle_range: 3.0
      raytrace_range: 3.5

  inflation:
    inflation_radius: 0.4
    cost_scaling_factor: 5.0